version: "3.8"

services:
  package-services:
    container_name: package-services
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    networks:
      - backend
    depends_on:
      - package-db

  package-db:
    container_name: package-db
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongodb_data:/data/db

networks:
  backend:
    external: true
volumes:
  mongodb_data:
